/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4SZfZS9P6Wu
 */
import { Button } from "@/components/ui/button"

export function home() {
  return (
    <div className="grid md:grid-cols-2 items-start justify-center gap-12 max-w-3xl mx-auto px-4">
      <div className="space-y-4">
        <h1 className="text-3xl font-bold">飲み会</h1>
        <p className="text-gray-500 dark:text-gray-400">
          あなたの家で楽しむための飲み会アプリ。ワイン、日本酒、カクテルのオプションがあります。
        </p>
      </div>
      <div className="space-y-4">
        <div className="flex items-center space-x-4">
          <div className="text-2xl font-bold">🍷</div>
          <div>
            <h2 className="font-semibold">ワイン</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">あなたの好みのワインを見つけましょう。</p>
          </div>
        </div>
        <div className="grid gap-4">
          <Button variant="outline">ワインの選択</Button>
        </div>
      </div>
      <div className="space-y-4">
        <div className="flex items-center space-x-4">
          <div className="text-2xl font-bold">🍶</div>
          <div>
            <h2 className="font-semibold">日本酒</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">あなたの好みの日本酒を見つけましょう。</p>
          </div>
        </div>
        <div className="grid gap-4">
          <Button variant="outline">日本酒の選択</Button>
        </div>
      </div>
      <div className="space-y-4">
        <div className="flex items-center space-x-4">
          <div className="text-2xl font-bold">🍹</div>
          <div>
            <h2 className="font-semibold">カクテル</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">あなたの好みのカクテルを見つけましょう。</p>
          </div>
        </div>
        <div className="grid gap-4">
          <Button variant="outline">カクテルの選択</Button>
        </div>
      </div>
    </div>
  )
}
